title: SciML Leeds SENSE training
logo: logo.png
description: 7th March 2024
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: https://gws-access.jasmin.ac.uk/public/sensecdt/eesjb/sense_ae.zip
  tar_url: http://example.com/download.zip
